config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # post "/questions", to: "questions#create"
  # patch "/questions/:id", to: "questions#update"
  # delete "/questions/:id", to: "questions#destroy"
  resources :questions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  # skip_before_action :verify_authenticity_token

  def index
    @questions = Question.all
  end

  def create
    question =
      Question.create(
        body: params[:question][:body],
        user_id: params[:question][:user_id]
      )

    redirect_to question_path(question)
  end

  def update
    @question = Question.find(params[:id])
    @question.update(
      body: params[:question][:body],
      user_id: params[:question][:user_id]
    )
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRailsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/destroy.html.erb
You are cool!

app/views/questions/index.html.erb
<h2>Questions</h2>

<% @questions.each do |question| %>
 <p>
  <%= link_to "Question #{question.id}", "/questions/#{question.id}"%>
  <span>
    <%=link_to "Link to #{question.id} with path helper ", question_path(id: question.id)%>
  </span>
  <span>
    <%=link_to "Another way to #{question.id} with path helper  ", question_path(question.id)%>
  </span>
  <span>
    <%=link_to "One more way to #{question.id} with path helper ", question_path(question)%>
  </span>
</p>
<% end %>

app/views/questions/new.html.erb
<h2>New Question</h2>

<form action="/questions" method="post" rows="5">
  <p><label for="question[body]">Question Text</label></p>
  <p><textarea name="question[body]"></textarea></p>
  <p><label for="question[user_id]">User Id</label></p>
  <p><input type="number" name="question[user_id]]"></p>
  <p><input type="submit" value="Create"></p>
</form>

<%= form_with model: @question do |form| %>
 <p><%= form.label :body, "Question text"%></p>
 <p><%= form.text_area :body, rows: 5%></p>

 <p><%= form.label :user_id %></p>
 <p><%= form.text_field :user_id %></p>

 <p><%= form.submit "Create" %></p>

 <% end%>

app/views/questions/show.html.erb
<h1>Question</h1>
<p><%= @question.body %></p>
<p>user_id: <%= @question.user_id %></p>
<p><%= link_to "All Questions", "/questions"%></p>
<p><%= link_to "All Questions using helper", questions_path%></p>

app/views/questions/update.html.erb
You are cool!!!